### ISSUE TITLE
Xiloader crashes when you lock Windows 10

### ISSUE THREAD

**Issue by Snugglesffxi** [DarkstarProject/xiloader#23]
OS windows 10 pro, locking system via windows key+L and using software menu via start button crashes the game without any warning, looks like it just performs a clean exit, no error message to be had... upon unlocking the computer for any length of time the game+xiloader is just no longer running. Repeated several times with both game in focus and out.

**Comment by zynjec** [comment]
This will happen with even the stock client, its due to how the DirectX device is handled by the engine, it doesn't gracefully handle pretty much anything happening to the device and just closes the game.

**Comment by Snugglesffxi** [comment]
oh that's sad, thank you!
