### ISSUE TITLE
windows 10 client crash

### ISSUE THREAD

**Issue by githubigssan** [DarkstarProject/xiloader#6]
disassembly:

626C3DD1  cmp         dword ptr [eax],ecx  

Call Stack :
>	d3d8.dll!626c3dd1() 	
 	[Frames below may be incorrect and/or missing, no symbols loaded for d3d8.dll]	
 	d3d8.dll!62699dba() 	
 	Ashita.dll!5b0a12be() 	
 	FFXiMain.dll!040e8b7c() 	
 	FFXiMain.dll!040f0d65() 	
 	uxtheme.dll!6eac8882() 	
 	uxtheme.dll!6eac87cc() 	
 	uxtheme.dll!6eac87d4() 	
 	user32.dll!747ce6dc() 	
 	user32.dll!747cebcb() 	
 	ntdll.dll!77c5dc2c() 	
 	KernelBase.dll!770cacb9() 	
 	user32.dll!747df648() 	
 	polcore.dll!10047ffd() 	
 	FFXiMain.dll!043e48d2() 	
 	FFXiMain.dll!040e1b6b() 	
 	FFXiMain.dll!040e15dc() 	
 	FFXiMain.dll!040f552b() 	
 	FFXiMain.dll!040f4d57() 	
 	FFXiMain.dll!040f4c39() 	
 	FFXiMain.dll!040f49d9() 	
 	FFXi.dll!00ea4e8d() 	
 	combase.dll!77904f60() 	
 	combase.dll!77904b91() 	
 	combase.dll!7790fdd2() 	
 	combase.dll!7790df17() 	
 	combase.dll!7790b532() 	
 	combase.dll!7790cb99() 	
 	pol.exe!00e94c5d() 	
 	pol.exe!00e94c98() 	
 	pol.exe!00e968cc() 	
 	kernel32.dll!77a762c4() 	
 	ntdll.dll!77c50609() 	
 	ntdll.dll!77c505d4()

**Comment by teschnei** [comment]
I can't do anything with this.  No repro steps... etc
